[package]
name = "kats"
version = "0.1.0"
authors = ["Vincent Hanquez <vincent@typed.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2"
num-bigint = "0.3"
thiserror = "1"
anyhow = "1"
hex = "0.4"
